### ISSUE TITLE
wait i dont understand how do we get shell? and how do we get connection?

### ISSUE THREAD

**Issue by AspectKraken** [paij0se/pairat#3]

**Comment by paij0se** [comment]
First you need to execute pairat, downloading the binary file or from source https://github.com/paij0se/pairat/releases/tag/v0.0.4, then you open the "server".

The server is gonna give you a ngrok link, and you are gonna to paste it in the cli client https://github.com/paij0se/pairat-cli
that is like a shell.

**Comment by AspectKraken** [comment]
so we are suppose to make the victim download the cli and paste our ngrok?

**Comment by paij0se** [comment]
no, it's the other way around, the victim has to download https://github.com/paij0se/pairat,  and you paste the ngrok link in the cli that the server(pairat) gives you, i made you a little drawing so you can understand. <img src="https://media.discordapp.net/attachments/786759600245309460/920898563179941959/Captura_de_pantalla_2021-12-15_233257.png?width=514&height=408">
